//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int MaKH { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập Họ tên")]
        [ Display(Name ="Họ tên")]
        public string Hoten { get; set; }

        [Required(ErrorMessage = "Nhập tên tài khoản")]
        [Display(Name = "Tên tài khoản")]
        public string TaiKhoan { get; set; }

        [Required(ErrorMessage ="Nhập mật khẩu")]
        [Display(Name = "Mật Khẩu")]
        public string MatKhau { get; set; }

        [Required(ErrorMessage = "Nhập lại mật khẩu")]
        [Display(Name = " Comfirm Mật Khẩu")]
        public string ComfirmMatKhau { get; set; }

        [Required(ErrorMessage = "Nhập email")]
        [Display(Name = "Email")]       
        public string Email { get; set; }

        [Required(ErrorMessage = "Nhập địa chỉ ")]
        [Display(Name = "Địa Chỉ")]
        public string DiaChi { get; set; }

        [Required(ErrorMessage = "Nhập số điện thoại")]
        [Display(Name = "Điện Thoại")]
        public string DienThoai { get; set; }

        [Required(ErrorMessage = "Nhập giới tính")]
        [Display(Name = "Giới Tính")]
        public string GioiTinh { get; set; }

        [Required(ErrorMessage = "Nhập ngày sinh")]
        [Display(Name = "Ngày sinh")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
